import re

def markdown_to_html(md):
    # Convert headers
    for i in range(6, 0, -1):
        md = re.sub(r'^#{' + str(i) + r'}\s*(.+?)\s*$', r'<h' + str(i) + r'>\1</h' + str(i) + r'>', md, flags=re.MULTILINE)
    
    # Convert bold and italic
    md = re.sub(r'\*\*(.+?)\*\*', r'<strong>\1</strong>', md)
    md = re.sub(r'\*(.+?)\*', r'<em>\1</em>', md)
    
    # Convert links [text](url)
    md = re.sub(r'\[(.+?)\]\((.+?)\)', r'<a href="\2">\1</a>', md)
    
    # Convert unordered lists (simple)
    lines = md.split('\n')
    in_list = False
    new_lines = []
    for line in lines:
        if line.startswith('- '):
            if not in_list:
                new_lines.append('<ul>')
                in_list = True
            new_lines.append('  <li>' + line[2:] + '</li>')
        else:
            if in_list:
                new_lines.append('</ul>')
                in_list = False
            new_lines.append(line)
    if in_list:
        new_lines.append('</ul>')
    md = '\n'.join(new_lines)
    
    # Convert paragraphs (any line not already wrapped)
    lines = md.split('\n')
    new_lines = []
    in_para = False
    for line in lines:
        if line.strip() == '':
            if in_para:
                new_lines.append('</p>')
                in_para = False
            new_lines.append('')
        elif line.startswith('<'):
            # Already HTML tag
            if in_para:
                new_lines.append('</p>')
                in_para = False
            new_lines.append(line)
        else:
            if not in_para:
                new_lines.append('<p>')
                in_para = True
                new_lines.append(line)
            else:
                new_lines.append(' ' + line)
    if in_para:
        new_lines.append('</p>')
    
    md = '\n'.join(new_lines)
    
    # Convert code blocks (```)
    # Simple: wrap in <pre><code>
    parts = md.split('```')
    for i in range(1, len(parts), 2):
        parts[i] = '<pre><code>' + parts[i] + '</code></pre>'
    md = '```'.join(parts)
    
    # Convert inline code `code`
    md = re.sub(r'`([^`]+)`', r'<code>\1</code>', md)
    
    return md

with open('book/manuscript.md', 'r') as f:
    md_content = f.read()

# Remove frontmatter
if md_content.startswith('---'):
    md_content = re.sub(r'^---\n.*?\n---', '', md_content, count=1, flags=re.DOTALL)

html_content = markdown_to_html(md_content)

# Wrap in HTML template
html_template = """<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>The OpenClaw Paradigm: AI-Native Development in Practice</title>
    <style>
        body {
            font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Oxygen, Ubuntu, Cantarell, 'Open Sans', 'Helvetica Neue', sans-serif;
            line-height: 1.6;
            max-width: 800px;
            margin: 0 auto;
            padding: 20px;
            color: #333;
        }
        h1, h2, h3, h4, h5, h6 {
            margin-top: 2em;
            margin-bottom: 0.5em;
            color: #2c3e50;
        }
        h1 { border-bottom: 2px solid #3498db; padding-bottom: 10px; }
        h2 { border-bottom: 1px solid #bdc3c7; padding-bottom: 5px; }
        p { margin-bottom: 1em; }
        ul, ol { padding-left: 2em; }
        code {
            background-color: #f8f9fa;
            padding: 2px 4px;
            border-radius: 3px;
            font-family: 'Courier New', monospace;
        }
        pre {
            background-color: #f8f9fa;
            padding: 15px;
            border-radius: 5px;
            overflow-x: auto;
        }
        a { color: #3498db; text-decoration: none; }
        a:hover { text-decoration: underline; }
        .toc {
            background-color: #f8f9fa;
            padding: 20px;
            border-radius: 5px;
            margin-bottom: 30px;
        }
        .footer {
            margin-top: 50px;
            padding-top: 20px;
            border-top: 1px solid #bdc3c7;
            font-size: 0.9em;
            color: #7f8c8d;
            text-align: center;
        }
    </style>
</head>
<body>
    <div class="toc">
        <h1>The OpenClaw Paradigm</h1>
        <h2>AI-Native Development in Practice</h2>
        <p><em>First Edition, February 2026</em></p>
        <p>This book was generated by the OpenClaw Books 8-Day Sprint, an autonomous AI writing project that completed research, writing, integration, and formatting in under 48 hours.</p>
        <p><a href="#table-of-contents">Table of Contents</a> | <a href="#introduction">Introduction</a></p>
    </div>
    <div id="content">
        {{CONTENT}}
    </div>
    <div class="footer">
        <p>© 2026 OpenClaw Community. Licensed under Creative Commons Attribution-NonCommercial-ShareAlike 4.0 International.</p>
        <p>Generated on 2026-02-13 by OpenClaw Books 8-Day Sprint.</p>
        <p>Word count: 88,271 | Chapters: 15</p>
    </div>
</body>
</html>"""

html_template = html_template.replace('{{CONTENT}}', html_content)

with open('book/book.html', 'w') as f:
    f.write(html_template)

print("HTML created: book/book.html")